### ISSUE TITLE
plotly 4.6.0 doesn't work

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.htmlwidgets#14]
It reports

```
Error in htmltools::renderDependencies(content$dependencies, "href") :
  Dependency jquery 1.11.3 does not have a usable source
trace:
stop("Dependency ", dep$name, " ", dep$version, " does not have a usable source")
htmltools::renderDependencies(content$dependencies, "href")
build.html(list(body = rendered$html, head = rendered$head, dependencies = deps),
    ocaps)
as.character.htmlwidget(x, ..., ocaps = FALSE)
as.character(x, ..., ocaps = FALSE)
print.htmlwidget(x)
function (x, ...)
UseMethod("print")(x)
```

I don't understand htmltools dependencies well enough to figure out where jquery is supposed to come from - it doesn't appear to be in the package any more?

It could be a bug in plotly, since backing out to 4.5.6 works (but that restores our Issue #2). But we should first assume we're doing something wrong here before raising an issue (and proposing a fix) there.

**Comment by gordonwoodhull** [comment]
I haven't looked to see whether this has to do with our changes - kind of doubt it, but it's worth checking too.

**Comment by useless5771** [comment]
@gordonwoodhull this issue is not fully resolved, we need to do some updates to shared.r - I commented on the pull request: https://github.com/att/rcloud.htmlwidgets/pull/15

**Comment by gordonwoodhull** [comment]
I have tested plotly 4.6-4.8 because we are currently having problems with 4.9.

They work (as of RCloud 2.1.3) so I'm closing this. Will open a new issue for plotly 4.9 since it looks unrelated.
