### ISSUE TITLE
Linked metricsgraphics plots don't work.

### ISSUE THREAD

**Issue by useless5771** [att/rcloud.htmlwidgets#16]
It should behave as the one of the examples: https://hrbrmstr.github.io/metricsgraphics/

To reproduce, run this and hover over any of the plots produced, both plots should highlight the time point that the mice points at.

`
set.seed(1492)
stocks <- data.frame(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4))

stocks2 <- data.frame(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4))

s1 <- stocks %>%
  mjs_plot(x=time, y=X, linked=TRUE, width=350, height=275) %>%
  mjs_line() %>%
  mjs_add_line(Y) %>%
  mjs_add_line(Z) %>%
  mjs_axis_x(xax_format="date") %>%
  mjs_add_legend(legend=c("X", "Y", "Z"))

s2 <- stocks2 %>%
  mjs_plot(x=time, y=X, linked=TRUE, width=350, height=275) %>%
  mjs_line() %>%
  mjs_add_line(Y) %>%
  mjs_add_line(Z) %>%
  mjs_axis_x(xax_format="date") %>%
  mjs_add_legend(legend=c("X", "Y", "Z"))

mjs_grid(s1, s2, ncol=2)

`

**Comment by useless5771** [comment]
I had a look at generated html and it looks correct (linked property is set and also target property has correct values) there are also no errors in JS console. 

I will have a look if this example works outside rcloud.

**Comment by useless5771** [comment]
Turns out that this is known issue: https://github.com/hrbrmstr/metricsgraphics/issues/52 verified that single-line linked plots work fine in rcloud.

**Comment by gordonwoodhull** [comment]
That's wild! How could they publish a example that doesn't work?

It also looks like the demo at github.io also just highlights one point whereas the package that installs via `install_github` highlights all three points at the current X position. 

So I wonder if there is a version mismatch.

**Comment by useless5771** [comment]
It looks like the version published to CRAN is 0.9.0 (https://cran.r-project.org/web/packages/metricsgraphics/index.html) and last release version 0.9.1 - which is over a year old - hasn't been published....

Hmm... this is very odd, the bug report refers to the version metricsgraphics_0.9.1 so the issue must have been there in the release version, but then I went through recent commits and didn't find any that could have fixed it...

**Comment by gordonwoodhull** [comment]
metricsgraphics seems to be another project that has given up on CRAN and is using devtools and [GitHub Releases](https://github.com/hrbrmstr/metricsgraphics/releases). 

I got the `.tar.gz` of both 0.9.1 and master, also tried devtools, same results, also in RStudio. So I think they have not released this feature yet (and I commented above).
