### ISSUE TITLE
ggplotly always creates a blank plot when called from a notebook

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.htmlwidgets#2]
plotly's ggplot support seems to require first rendering the ggplot, which creates a graphic device context and a blank spot in the notebook.

can we suppress this? avoid this? suggest that plotly more thoroughly override the graphics device?

**Comment by s-u** [comment]
You can setup a non-screen device (e.g. `pdf()`) as a work-around and discard the output. Yes, ideally, plotly should not mess with the active device and set one internally if it really requires one.

**Comment by gordonwoodhull** [comment]
Cool, thanks @s-u. Is there a workaround we can suggest people use within their notebook? I hesitate to add this kind of messiness to the package, which is currently pretty clean.

**Comment by s-u** [comment]
Do you have an example? I'm wondering if this is explicit or not - sometimes code inadvertently queries `par()` which in turn creates a device if not present. That case would be different and more easy to handle than if `plotly` actually requires proper rendering into a device. As I think of it, we're already using `Cairo` so using

```r
Cairo(type="raster")
## your code here
dev.off()
```

will have the desired nil-effect, but we could create some syntactic sugar for it in case we can't detect the need automatically.

**Comment by gordonwoodhull** [comment]
Yes, that seems to do the trick. Thanks!

https://rcloud.social/edit.html?notebook=1675618944a5a5abc0e57a70b3a3785b

vs.

https://rcloud.social/edit.html?notebook=1675618944a5a5abc0e57a70b3a3785b&tag=no-suppress

**Comment by gordonwoodhull** [comment]
It's actually just the `ggplotly` call that needs to be wrapped:

```r
library(plotly)

dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
foo <- qplot(carat, price, data=dsamp, colour=clarity)

Cairo(type="raster")
ggplotly(foo)
dev.off()
```
https://rcloud.social/edit.html?notebook=5487fae1c936f32e55e061ad1cc301e9

**Comment by gaborcsardi** [comment]
We can do this automatically in `print.htmlwidgets` I guess.

**Comment by gordonwoodhull** [comment]
Thanks @gaborcsardi. It seems to be only ggplotly that has the problem. Presumably it is playing the graphics commands and capturing them somehow.

I'd hesitate to do this for all the "well-behaved" packages that don't mess with device contexts in producing their html.

**Comment by gaborcsardi** [comment]
I would just do it for `plotly`. We can probably detect the type of the widget.

**Comment by s-u** [comment]
AFAICT it is really a bug in `plotly::gg2list` - they are already creating a new device so I think the bug is that they try to get dimensions for a non-existing device before they create their internal bitmap device (it is triggered by `unitConvert()`). I think they only need to add a guard along the lines of `if (is.null(dev.list()) { ... set width/height defaults }` as to not trigger an inadvertent device creation.

**Comment by s-u** [comment]
I have filed a `plotly` issue https://github.com/ropensci/plotly/issues/829 on this

**Comment by s-u** [comment]
BTW: The issue shows up only when you don't set the dimensions, so probably the best recommendation to users for now is to tell them to set the dimensions, e.g.:

```r
library(plotly)

dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
foo <- qplot(carat, price, data=dsamp, colour=clarity)

ggplotly(foo, 800, 400) 
```

**Comment by gaborcsardi** [comment]
While the issue is in `plotly`, we can still a (temporary) workaround, it is easy:

```r
if (inherits(x, "plotly")) { 
 Cairo(...)
...
}
```

**Comment by s-u** [comment]
I'm not actually sure that you can avoid it ahead of time, because the device is opened *before* the `plotly` object is created - so it's not the print time, it's the construction time.

**Comment by cpsievert** [comment]
Hopefully https://github.com/ropensci/plotly/commit/52800f9878f9c9fd7a8767bb49763ea82ba1dbdb fixes the problem. Thanks for bringing this to my attention.

Previously I was opening the default graphics device, but I definitely agree it would be preferable to always use `Cairo()`, so I've added it as a dependency.

BTW, is there much of advantage of using `Cairo(type="raster")` over the default (png)?

**Comment by gordonwoodhull** [comment]
This appears to be fixed. Thanks @cpsievert, @gaborcsardi, @s-u!!!

**Comment by gordonwoodhull** [comment]
This appears to have returned with plotly 4.6.0

**Comment by cpsievert** [comment]
@gordonwoodhull would you mind checking with the latest github version of plotly? I'm aiming for CRAN release at the end of the week and want to get this right...

**Comment by gordonwoodhull** [comment]
Great, looks like it will work again in 4.7.0. Thanks @cpsievert!
