### ISSUE TITLE
Unable to load Leaflet JS plugin

### ISSUE THREAD

**Issue by jfrabetti** [att/rcloud.htmlwidgets#22]
When I try loading the leaflet-heat.js plugin using the code on [this page](https://gist.github.com/jcheng5/c084a59717f18e947a17955007dc5f92), I get the following error:

    Error in path.expand(path) : invalid 'path' argument
    trace:
    path.expand(path)
    normalizePath(path)
    is_in_path(path, parent)
    where_in_path(file, .libPaths())
    FUN(X[[i]], ...)
    lapply(htmltools::htmlDependencies(html), rcloudHTMLDependency)
    as.character.htmlwidget(x, ..., ocaps = FALSE, rcloud_htmlwidgets_print = TRUE)
    as.character(x, ..., ocaps = FALSE, rcloud_htmlwidgets_print = TRUE)
    print.htmlwidget(x)
    function (x, ...) 
    UseMethod("print")(x)
On my RCloud instance, I tried also loading leaflet-heat.js from a file as an Asset and from my directory - I get the error either way. I also tried installing the dev version of htmlwidgets as suggested, but the error is the same.

**Comment by gordonwoodhull** [comment]
Hi Jo! Could you create an example notebook on rcloud.social please?

Mats (@useless5771), could you have a look please?

**Comment by jfrabetti** [comment]
[Here is the example notebook](https://rcloud.social/edit.html?notebook=cda48865aedbcb85ab44645069cd13ab) - the issue is happening in the second jcheng5 [example](https://gist.github.com/jcheng5/c084a59717f18e947a17955007dc5f92) (**cell 3**); the first example (cell 2) gave me an error as well until I installed the most recent version of leaflet.

**Comment by gordonwoodhull** [comment]
Fixed in 1.0.4
