### ISSUE TITLE
parcoords comes up blank on some instances

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.htmlwidgets#6]
it is working on my local but comes up blank on rcloud.social & research. 

i don't see how this could be a proxification issue - maybe just a fluke that it works on my local.

**Comment by s-u** [comment]
Do you have any code to reproduce?

**Comment by gordonwoodhull** [comment]
Yop, just the basic example

```r
library(parcoords)

data(mtcars)

parcoords(
  mtcars
  ,reorderable = T
  ,brushMode = "2d-strums"
)
```

**Comment by gordonwoodhull** [comment]
Note I installed it using `devtools::install_github("timelyportfolio/parcoords")` across the instances I tried, and I did see it pulling in `jsonlite` and `Rcpp`, so it could be some build issue. Didn't notice any errors but there was a lot of output.

**Comment by useless5771** [comment]
I am unable to reproduce this in my dev environment. I installed parcoords using devtools::install_github("timelyportfolio/parcoords")

and code snippet just runs fine and displays a plot.

Session info for reference:
> R version 3.2.3 (2015-12-10)
> Platform: x86_64-pc-linux-gnu (64-bit)
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods  
> [8] base     
> other  attached packages:
>  [1] parcoords_0.4.0            rcloud.flexdashboard_1.0.0
>  [3] rcloud.rmd_1.0.0           rcloud.htmlwidgets_1.0.0  
>  [5] rcloud.notebook.info_0.1   rcloud.enviewer_0.1       
>  [7] rcloud.viewer_0.1          rmarkdown_1.4             
>  [9] githubgist_1.0-3           rediscc_0.1-4             
> [11] sendmailR_1.2-1            RCurl_1.95-4.8            
> [13] bitops_1.0-6               httr_1.2.1                
> [15] markdown_0.7.11            knitr_1.15.1              
> [17] png_0.1-8                  Rserve_1.8-5              
> [19] FastRWeb_1.1-2             Cairo_1.5-9               
> [21] rcloud.support_1.7-0       rjson_0.2.15              
> [23] base64enc_0.1-4           
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.10           rcloud.r_0.0.1         unixtools_0.1-1       
>  [4] tools_3.2.3            digest_0.6.12          uuid_0.1-2            
>  [7] gist_1.0-0             jsonlite_1.4           evaluate_0.10         
> [10] PKI_0.1-5              yaml_2.1.14            curl_2.5              
> [13] stringr_1.2.0          htmlwidgets_0.8        flexdashboard_0.5     
> [16] rprojroot_1.2          R6_2.2.0               Rook_1.1-1            
> [19] rcloud.python_0.0.1    github_0.9.8           magrittr_1.5          
> [22] backports_1.0.5        htmltools_0.3.5        mime_0.5              
> [25] brew_1.0-6             stringi_1.1.5          rcloud.rmarkdown_0.0.1

**Comment by gordonwoodhull** [comment]
Yeah that's the same result I got on my local. For whatever reason, it only fails on the instances which actually matter.

For example, the public instance:
https://rcloud.social/edit.html?notebook=26f5fff14d9582eb75c5f4e1505c96a3

**Comment by useless5771** [comment]
Indeed the plot fails to display on rcloud.social. There are the following errors in JS console:

> parcoords.js Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.min.js Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.svg.multibrush.js Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.parcoords.js Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.parcoords.css Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.min.js Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.parcoords.css Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.svg.multibrush.js Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.parcoords.js Failed to load resource: the server responded with a status of 404 (Code 404)
> parcoords.js Failed to load resource: the server responded with a status of 404 (Code 404)
> d3.parcoords.css Failed to load resource: the server responded with a status of 404 (Code 404)


Session info:

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.5 LTS
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods  
> [8] base     
> 
> other attached packages:
>  [1] parcoords_0.4.0            rcloud.rmd_1.0.0          
>  [3] rcloud.flexdashboard_1.0.0 rcloud.logo_0.1.1         
>  [5] rcloud.rcap_0.3.12         rcloud.htmlwidgets_1.0.0  
>  [7] rcloud.notebook.info_0.1   rcloud.enviewer_0.1       
>  [9] rcloud.viewer_0.1          rmarkdown_1.3             
> [11] githubgist_1.0-3           rediscc_0.1-4             
> [13] sendmailR_1.2-1            RCurl_1.95-4.8            
> [15] bitops_1.0-6               httr_1.2.1                
> [17] markdown_0.7.7             knitr_1.15.1              
> [19] png_0.1-8                  Rserve_1.8-5              
> [21] FastRWeb_1.1-2             Cairo_1.5-9               
> [23] rcloud.support_1.7-0       rjson_0.2.15              
> [25] base64enc_0.1-4           
> 
> loaded via a namespace (and not attached):
>  [1] Rook_1.1-1             rcloud.r_0.0.1         htmltools_0.3.5       
>  [4] yaml_2.1.14            rcloud.sh_0.1-1        withr_1.0.1           
>  [7] uuid_0.1-2             flexdashboard_0.3      rcloud.python_0.0.1   
> [10] stringr_1.0.0          devtools_1.10.0        htmlwidgets_0.8       
> [13] codetools_0.2-15       evaluate_0.10          memoise_1.0.0         
> [16] gist_1.0-0             curl_1.2               rcloud.rmarkdown_0.0.1
> [19] Rcpp_0.12.8            backports_1.0.5        unixtools_0.1-1       
> [22] jsonlite_1.2           PKI_0.1-4              mime_0.5              
> [25] brew_1.0-6             digest_0.6.10          stringi_1.1.1         
> [28] rprojroot_1.2          tools_3.3.2            magrittr_1.5          
> [31] github_0.9.8           rcloud.web_1.0-1       R6_2.2.0              
> [34] git2r_0.14.0   

I will investigate this further.

Is this a regression? I.e., has parcoords ever worked in these environments?

**Comment by gordonwoodhull** [comment]
No, I don't think it has ever worked in those environments. It could be a bug in `shared.R` or there could be something strange about the [proxified environment](https://github.com/att/rcloud/wiki/ProxifiedSetup) where these kinds of requests don't work.

The `_htmlwidgets` path prefix for `shared.R` is obviously rather new.

**Comment by useless5771** [comment]
It looks like the _htmlwidgets URLs are not correctly handled for user-installed packages in shared.R.

We need to add it here:

```
  ## Try _htmlwidgets/pkg/ first
  fn <- ""
  if (pkg %in% c("_htmlwidgets")) {
    path <- c(substring(pkg, 2), pex[-1])
    fn <- system.file(package = pex[1], do.call(file.path, as.list(path)))
  }

  ## Otherwise try pkg/www, and finally the user library
  base <- paste(c("www", pex), collapse="/")
  if (!nzchar(fn) &&
      !nzchar(fn <- system.file(base, package=pkg)) && length(pex) > 1) {
      ## try to interpret as user/pkg
      usr <- pkg
      pkg <- pex[1]
      base <- paste(c("www", pex[-1]), collapse="/")
      lib <- rcloud.home("library", user=usr)
      if (!file.exists(fn <- file.path(lib, pkg, base)))
          fn <- ""
  }
```

I will update shared.R and raise pull request.

**Comment by useless5771** [comment]
As this code sits in rcloud repository I raised a pull request in there: https://github.com/att/rcloud/pull/2405

**Comment by gordonwoodhull** [comment]
Makes sense, thanks!
